- hosts: localhost
  gather_facts: false
  vars_files:
    - settings.yml
  tasks:
    - name: start rabbitmq server
      docker:
        image: larsks/rabbitmq
        name: rabbitmq
        state: running
    - name: start database server
      docker:
        image: mysql
        name: mysql
        state: running
        env:
          - MYSQL_ROOT_PASSWORD={{MYSQL_ROOT_PASSWORD}}
    - name: get database server ip
      command: docker inspect --format '{{ .NetworkSettings.IPAddress }}' mysql
      register: mysqlip
    - name: wait for database server to become active
      wait_for: host={{mysqlip.stdout}} port=3306 state=present
    - name: initialize keystone database
      shell: >
        docker run --link mysql:mysql -i --rm
        -e KEYSTONE_DB_PASS={{KEYSTONE_DB_PASS}}
        -e MYSQL_ROOT_PASSWORD={{MYSQL_ROOT_PASSWORD}}
        mysql bash < init-keystone.sh
    - name: initialize glance database
      shell: >
        docker run --link mysql:mysql -i --rm 
        -e GLANCE_DB_PASS={{GLANCE_DB_PASS}}
        -e MYSQL_ROOT_PASSWORD={{MYSQL_ROOT_PASSWORD}}
        mysql bash < init-glance.sh
    - name: start keystone server
      docker:
        image: larsks/keystone
        name: keystone
        links:
          - mysql
        env:
          - KEYSTONE_DB_PASS={{KEYSTONE_DB_PASS}}
          - KEYSTONE_ADMIN_TOKEN={{KEYSTONE_ADMIN_TOKEN}}
    - name: get keystone server ip
      command: docker inspect --format '{{ .NetworkSettings.IPAddress }}' keystone
      register: keystoneip
    - name: wait for keystone server to become active
      wait_for: host={{keystoneip.stdout}} port=5000 state=present
    - name: initialize keystone
      shell: >
        docker run
        --link mysql:mysql
        --link keystone:keystone
        -e KEYSTONE_ADMIN_TOKEN={{KEYSTONE_ADMIN_TOKEN}}
        -e KEYSTONE_ADMIN_PASS={{KEYSTONE_ADMIN_PASS}}
        --rm -i larsks/os-apiclient bash < setup-keystone.sh
    - name: add keystone entries for glance
      shell: >
        docker run
        --link mysql:mysql
        --link keystone:keystone
        -e KEYSTONE_ADMIN_PASS={{KEYSTONE_ADMIN_PASS}}
        -e GLANCE_KEYSTONE_PASS={{GLANCE_KEYSTONE_PASS}}
        --rm -i larsks/os-apiclient bash < setup-glance.sh
    - name: start glance server
      docker:
        image: larsks/glance
        name: glance
        links:
          - mysql
          - keystone
          - rabbitmq:amqphost
        env:
          - GLANCE_DB_PASS={{GLANCE_DB_PASS}}
          - GLANCE_KEYSTONE_PASS={{GLANCE_KEYSTONE_PASS}}

