- hosts: localhost
  gather_facts: false
  vars_files:
    - settings.yml
  tasks:
    # the rabbitmq server has no dependencies, so we start it first.
    - name: start rabbitmq server
      docker:
        image: larsks/rabbitmq
        name: rabbitmq
        state: running

    # everything else is going to need a database server, so we create one here
    # using the offical mysql image.
    - name: start database server
      docker:
        image: mysql
        name: mysql
        state: running
        env:
          - MYSQL_ROOT_PASSWORD={{MYSQL_ROOT_PASSWORD}}

    # mysql takes a few seconds to start up.  the next two tasks ask docker for
    # the ip address of the mysql container and then wait for the mysql port to
    # become available.
    - name: get database server ip
      command: docker inspect --format '{{ .NetworkSettings.IPAddress }}' mysql
      register: mysqlip
    - name: wait for database server to become active
      wait_for: host={{mysqlip.stdout}} port=3306 state=present

    # now we create databases and set up some database credentials.  note 
    # here that we are passing in credentials via environment variables (so
    # that we don't need to hardcode the credentials into our scripts).
    - name: initialize keystone database
      shell: >
        docker run --link mysql:mysql -i --rm
        -e KEYSTONE_DB_PASS={{KEYSTONE_DB_PASS}}
        -e MYSQL_ROOT_PASSWORD={{MYSQL_ROOT_PASSWORD}}
        mysql bash < init-keystone.sh
    - name: initialize glance database
      shell: >
        docker run --link mysql:mysql -i --rm 
        -e GLANCE_DB_PASS={{GLANCE_DB_PASS}}
        -e MYSQL_ROOT_PASSWORD={{MYSQL_ROOT_PASSWORD}}
        mysql bash < init-glance.sh

    # now that the database is available, we can start a keystone instance.  we
    # are passing in the keystone database password and admin token as
    # environment variables; these will be used by a sysinit script to 
    # configure keystone.
    - name: start keystone server
      docker:
        image: larsks/keystone
        name: keystone
        links:
          - mysql
        env:
          - KEYSTONE_DB_PASS={{KEYSTONE_DB_PASS}}
          - KEYSTONE_ADMIN_TOKEN={{KEYSTONE_ADMIN_TOKEN}}

    # wait for keystone to become available before we continue.
    - name: get keystone server ip
      command: docker inspect --format '{{ .NetworkSettings.IPAddress }}' keystone
      register: keystoneip
    - name: wait for keystone server to become active
      wait_for: host={{keystoneip.stdout}} port=5000 state=present

    # create some basic keystone entities, like an admin tenant/role/user and
    # the keystone entries in the service catalog.
    - name: initialize keystone
      shell: >
        docker run
        --link mysql:mysql
        --link keystone:keystone
        -e KEYSTONE_ADMIN_TOKEN={{KEYSTONE_ADMIN_TOKEN}}
        -e KEYSTONE_ADMIN_PASS={{KEYSTONE_ADMIN_PASS}}
        --rm -i larsks/os-apiclient bash < setup-keystone.sh

    # create keystone users and service catalog entries for glance.
    - name: add keystone entries for glance
      shell: >
        docker run
        --link mysql:mysql
        --link keystone:keystone
        -e KEYSTONE_ADMIN_PASS={{KEYSTONE_ADMIN_PASS}}
        -e GLANCE_KEYSTONE_PASS={{GLANCE_KEYSTONE_PASS}}
        --rm -i larsks/os-apiclient bash < setup-glance.sh

    # start the glance server.
    - name: start glance server
      docker:
        image: larsks/glance
        name: glance
        links:
          - mysql
          - keystone
          - rabbitmq:amqphost
        env:
          - GLANCE_DB_PASS={{GLANCE_DB_PASS}}
          - GLANCE_KEYSTONE_PASS={{GLANCE_KEYSTONE_PASS}}

